name: Create API Docs
on:
   workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
   build:
      # The type of runner that the job will run on
      runs-on: ubuntu-latest

      steps:
         - uses: actions/checkout@v2
         - name: Setup node 12
           uses: actions/setup-node@v2
           with:
              node-version: 12.x
         - run: |
              npm install
              npm run create_API_doc
         - name: Commit and push changes
           run: |
              git config --global user.name "jhamadhav"
              git config --global user.email "contact@gmail.com"
              git add -A
              git commit -m "API Docs created"
              git push
